version: '2'
services:

  mysql:
    image: mysql
    container_name: mysql

  php:
    container_name: php
    volumes:
      - ./:/usr/share/nginx/www
    links:
      - mysql

  nginx:
    container_name: nginx
    build: images/nginx-php
    ports:
      - 80:80
    links:
      - php
    volumes:
      - ./:/usr/share/nginx/www
