version: '2'
services:

  php:
    container_name: php
    build: docker/php
    external_links:
      - mysql
    volumes:
      - ./:/usr/share/nginx/www

  nginx:
    container_name: nginx
    build: docker/nginx
    links:
      - php
    volumes:
      - ./:/usr/share/nginx/www
    environment:
      VIRTUAL_HOST: backend

networks:
  default:
    external:
      name: myapp
