version: '2'
services:

  php:
    container_name: php
    volumes:
      - ./:/usr/share/nginx/www

  nginx:
    container_name: nginx
    build: images/nginx-php
    ports:
      - 80:80
    links:
      - php
    volumes:
      - ./:/usr/share/nginx/www
