version: '2'
services:

  php:
    image: php:7-fpm
    volumes:
      - ./:/usr/share/nginx/www

  nginx:
    build: docker/images/nginx
    ports:
      - 80:80
    links:
      - php
    volumes:
      - ./:/usr/share/nginx/www
    environment:
      VIRTUAL_HOST: backend

networks:
  default:
    external:
      name: myapp
