version: '2'
services:

  redis:
    image: redis
    container_name: redis

  mysql:
    image: mysql
    container_name: mysql

  php:
    container_name: php
    links:
      - mysql
    working_dir: /usr/share/nginx/www
    volumes:
      - ./:/usr/share/nginx/www

  nginx:
    container_name: nginx
    links:
      - php:fpm
    volumes:
      - ./:/usr/share/nginx/www
